### ISSUE TITLE
Hide undefined tooltip attributes

### ISSUE THREAD

**Issue by fxwiegand** [vega/vega-tooltip#251] opened 2019-06-25 20:39 UTC
I am working on a vega-lite visualization with data that can have quite a few attributes. Not all of my data needs to have all attributes set so some could be undefined. My data could look like this:

```
[
    {"a":1, "b":"A", "c":"U"},
    {"a":3, "b":"X"},
    {"a":2, "c":"Z", "d":"bar"}
]
```

I would like to display all fields (that are actually defined and hide the undefined values) in the tooltip like this:
```
    "tooltip": [
      {"field": "a", "type": "quantitative"},
      {"field": "b", "type": "nominal"},
      {"field": "c", "type": "nominal"},
      {"field": "d", "type": "nominal"}
    ] 
```

As i understand, the vega-tooltip handler checks every field for null or empty, but before that, vega-Lite somehow sets not existing keys to the value "undefined" that is then displayed.

See an example in the vega online editor [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgE6Asl2Ex3PJcTcA7oyXUwL3bGSE3WzB0JU0wVEYxHTBCINoxByVYOjUNSE1rTBxgSAp0MVYdbDAAbQ0IUAgISCyARnUqqHZsc1TGyHgWgC1IcrAAXwaqyqqa7Gkh6uasSAANXsbBvpHqrIAmSahOmZ7N9Jb2dF0Fqv6QAF0QJeqMXQBrYsgAjzw2qGQleG5ND2pilagAA9-pAAGaMZBiTSPTCqKB4ACesUeAEdWCEjHhrIwqJBrqM8NxuGIjIRimVGhUwRCoTC1PCkchUeilJjsbj8Y0cuDIdDTM04ZBEcjTEpuBElPk8ZsqTzaaZOoLhUzReKPFLOcNqbzHtClYzHmKJRq+ucwBozmcgA).

**Comment by kanitw** [comment] 2019-06-26 05:43
(Transferred to vega-tooltip)

**Comment by fxwiegand** [comment] 2019-06-26 08:27
I think this is a vega-lite issue since vega-lite itself sets the non existing fields to (the string) undefined and not even the value `undefined`. 
The possible vega-tooltip issue is not checking for the value `undefined` right [here](https://github.com/vega/vega-tooltip/blob/master/src/Handler.ts#L69-L73).

**Comment by domoritz** [comment] 2019-06-26 15:03
I agree it could be both. Do you want to step through the code and see what needs to change?

**Comment by domoritz** [comment] 2019-06-26 17:06
I agree it could be both. Do you want to step through the code and see what needs to change?

**Comment by fxwiegand** [comment] 2019-07-01 08:57
I just found out that the line I referenced above is checking for `undefined` with `value == null` ([explanation here](https://stackoverflow.com/questions/28975896/is-there-a-dedicated-function-to-check-null-and-undefined-in-typescript)). 

> The possible vega-tooltip issue is not checking for the value `undefined` right [here](https://github.com/vega/vega-tooltip/blob/master/src/Handler.ts#L69-L73).

Since the tooltip handler is displaying the string undefined it must have been stringified by **vega-lite** somewhere ([maybe here?](https://github.com/vega/vega-lite/blob/1c0e284081eb03684bdd7fc753e7ca1b7852afcc/src/channeldef.ts#L944-L979)). For that i would suggest moving this issue back to vega-lite.

I'd like to dive deeper into finding the problem where `undefined` is stringified but i am currently working on by bachelor thesis which is quite time consuming.

**Closed** 2019-07-04 11:31 UTC

**Comment by fxwiegand** [comment] 2019-10-30 15:14
Is the vega online editor still using an old version? The issue with the example I mentioned when i started the issue is still there.

> See an example in the vega online editor [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgE6Asl2Ex3PJcTcA7oyXUwL3bGSE3WzB0JU0wVEYxHTBCINoxByVYOjUNSE1rTBxgSAp0MVYdbDAAbQ0IUAgISCyARnUqqHZsc1TGyHgWgC1IcrAAXwaqyqqa7Gkh6uasSAANXsbBvpHqrIAmSahOmZ7N9Jb2dF0Fqv6QAF0QJeqMXQBrYsgAjzw2qGQleG5ND2pilagAA9-pAAGaMZBiTSPTCqKB4ACesUeAEdWCEjHhrIwqJBrqM8NxuGIjIRimVGhUwRCoTC1PCkchUeilJjsbj8Y0cuDIdDTM04ZBEcjTEpuBElPk8ZsqTzaaZOoLhUzReKPFLOcNqbzHtClYzHmKJRq+ucwBozmcgA).

**Comment by domoritz** [comment] 2019-11-04 05:26
Vega-Tooltip now ignores undefined properties. However, Vega-Lite converts `undefined` to `"undefined"` so that users don't accidentally miss it. See https://github.com/vega/vega-lite/pull/5147 for the discussion about this. 

Here is an [example in Vega that hides undefined values](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAgmAToCydYQA23PMcTcA7oxnUw99bGSFH5sOhnKYKiMlmpghL60ltYysHQKSpDs6PAA1tTq3KwB2FAOiMzICRCQhOjKys7UuaKKJU7KLLkATAAMrXW4yIzU+C0dibB4AJ6huZDwyNHFKqaYOADaShCgEGtQMuioRfrSrOqTAPqtM+uQFOiWrGq5S+vrwJDzYACM8lDs4wYKUPDjAFqQAC+nXuYEezwAzO8kuMABrA0H3CEtGF-fSAmHKcbJdTA5ZrAC6BJBBNW90gm2242Uc2OpzWkD2Bx2UGZRxOSJKeHU-lgADNuOpULcCQ8xRSRhFxvyQnhzAywZBkAAPQh4-SMWAANUujGUAApaXhWKgFgAdJ6WwkASjAADJ7WAtQAxZyFA0AamNpotVsgtsgEogQIlxPWoYghM6TJ6m0ssFujyprMgKB6fRhrEIxtT6d6eGB0cSGHUqUTizJEspW1TpfLiqgUtTsGGqHY3EsjaZIzGi1K3GcheLSv5mRFOEexuekGn9NJSuQMng3FUuXJSuzufXwcZ3DK8GYw3X50u11yrToAHYF2DGbLppPT1dUzy+WV1EvC7e72yedxUlZR4LhfcYAGIABZ4CvAAOdAYMRXduW4TsdEIHdfzOWA40ucZgEtdBLRwQVhVMI1TF9AjrXeS1LRtGikiIsAfTNS12GosBLXgJiWL9biAwY5QeIo1jZ2tIEg0wsAfzvSAVRPEw+ygeSYVlKZsX0TAZKVY8n2w6h43GfNMygVBWEsQscEvURIzvWyIxJJQRzZeBLhuStxSVFNxhU6tm3GSxnGQdA8S5FRuAwZwT2nGk6U5KA1MsDSoC0sLIF5FxWQWDpwVjAzcP0BomiBZyzhkRhJlyHlrjSgAvcxuCq9RrkcqMY3QFV3LAO41g3RlFNTXylSFRgvxxGw8Ai7sMn1Jqar8irUgAYSyGRLNy-TDP0SYQgNIrEFICDWhtRClWUCL0Ci4jLk8NLLHQdgpgrMB+Ru5A0owFUAFEVXlNaLw+5wfr+9aBiVHQ0me16E3e6taucVR5KskkkT6koBp87sRrG-QOwIKa0pm5Loduha8CUp5u3ux7LBdK5YEQObYaVampgAeSodR7vQnBquZyVFpW7J1seTaCt+bpLD2-UWEO47TopeGAlVC9WrAZyJlkWVqifZI0gyVbksgfJCnxIEgA) (I just modified the expression in the generated Vega).

**Comment by fxwiegand** [comment] 2019-11-04 08:27
So there is currently no way using only Vega-Lite to hide properties that are not defined for every mark?

**Comment by fxwiegand** [comment] 2020-01-30 14:02
So I cannot use Vega-Lite for displaying data sets that only share some attributes. No chance the conversion from `undefined` to `"undefined"` could be modified to be optional so that users are able to choose for themselves what will be displayed and what will be hidden.

**Comment by domoritz** [comment] 2020-01-30 19:56
I'm happy to revise the behavior. I don't have the cycles to think through all the alternatives and implement them but I would be thrilled if you took a stab at laying out the design space, define what the expected behavior in different cases is, how we ensure compatibility with axes, and decide whether Vega-Lite or Vega-Tooltip need to change. How does that sound? I would really appreciate your help here!

**Comment by jerinjjose** [comment] 2020-05-04 03:45
Any Updates in this?
I am also facing the similar issue. Is there any way to hide the tooltip values that are not available in the data source?
I am stuck in development because of this.

**Comment by domoritz** [comment] 2020-05-04 21:18
See my comment above. I’d love to have some help on thinking though the design space.

**Comment by laysauchoa** [comment] 2021-03-03 16:28
I am interested to see if there is any news about it.

**Comment by Markweese** [comment] 2022-04-29 20:28
I'm currently on vega-tooltip v0.27.0 and still experiencing the issue, is this still waiting to be resolved, or am I missing something?

**Comment by domoritz** [comment] 2022-05-01 00:17
See my comment in https://github.com/vega/vega-tooltip/issues/251#issuecomment-580426919

**Comment by Markweese** [comment] 2022-05-02 16:36
> See my comment in [#251 (comment)](https://github.com/vega/vega-tooltip/issues/251#issuecomment-580426919)

When an object is passed with undefined fields, vega-lite is parsing the value to `NaN`, which then passes the `value == null || value === ''` check in the [aforementioned line of code](https://github.com/vega/vega-tooltip/issues/251#issuecomment-507178434) in the `vega-tooltip` `Handler.ts` file - a possible solution would be to add an `|| isNaN(value)` check to the if block to remove undefined items from the tooltip. To address the different questions you outlined in your comment:

what the expected behavior in different cases is:
- if the value is undefined in an object, vega-lite will parse it to `NaN`, vega-tooltip will catch the item in the `tooltipHandler` method and remove the item from the tooltip
how we ensure compatibility with axes:
- don't have enough contextual knowledge to answer this adequately - but I would expect vega-lite to exclude `NaN` values from any axes calculations
decide whether Vega-Lite or Vega-Tooltip need to change:
- vega-tooltip change

**Comment by Markweese** [comment] 2022-05-05 15:35
> See my comment in [#251 (comment)](https://github.com/vega/vega-tooltip/issues/251#issuecomment-580426919)

Looks like my version of vega-lite parses undefined fields to `NaN` - so adding an `isNaN(value)` check  to the [aforementioned line of code](https://github.com/vega/vega-tooltip/issues/251#issuecomment-505775318) in vega-tooltip would negate. Not sure how this would effect your "ensure compatibility with axes" point, but I feel like excluding the field, rather than showing `<field>: NaN` in the tooltip would be desirable for my use case (and probably others).
